### ISSUE TITLE
Despite the README, this actually works on PowerShell 7

### ISSUE THREAD

**Issue by han44-illinois** [engrit-illinois/Get-AppSupersedence#2]
Just wanted to leave a note. I just tried this with the `-Computer` parameter and it worked on PowerShell 7.

I ran `Get-AppSupersedence -Computer "eh-406b1-01"` with no issues.

**Comment by mmseng** [comment]
Most likely your results were inaccurate.

The use of `-Computer` is 5.1 dependent due to a reliance on `Get-WmiObject`. See: https://github.com/engrit-illinois/Get-AppSupersedence/blob/876468071b8a655c06a1568739759f8527f59145/Get-AppSupersedence.psm1#L397

**Comment by mmseng** [comment]
I  updated the readme to be more explicit in why 5.1 is required for the `-Computer` parameter: https://github.com/engrit-illinois/Get-AppSupersedence/commit/ad7641b8df6604ff8981e56a5ad1a6ee0c23dae3

To be clear, usage of the module omitting the `-Computer` parameter is still "untested" but may still work as intended, as there's no such explicit problem with the other non `-Computer` usages, outside of whatever native PS version support issues may be present in the user's ConfigurationManager module.
